/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/pairing`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ExpoReloadButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ReloadButton`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/patch-reanimated`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/assets`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/controls` | `/controls`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/keyboard` | `/keyboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screen` | `/screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trackpad` | `/trackpad`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/pairing`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/ExpoReloadButton`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/ReloadButton`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/utils/patch-reanimated`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/assets`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/controls` | `/controls`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/keyboard` | `/keyboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/screen` | `/screen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trackpad` | `/trackpad`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/pairing${`?${string}` | `#${string}` | ''}` | `/../components/ui/index${`?${string}` | `#${string}` | ''}` | `/../components/ui/ExpoReloadButton${`?${string}` | `#${string}` | ''}` | `/../components/ui/ReloadButton${`?${string}` | `#${string}` | ''}` | `/../src/utils/patch-reanimated${`?${string}` | `#${string}` | ''}` | `/../constants/assets${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/controls${`?${string}` | `#${string}` | ''}` | `/controls${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/keyboard${`?${string}` | `#${string}` | ''}` | `/keyboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/screen${`?${string}` | `#${string}` | ''}` | `/screen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trackpad${`?${string}` | `#${string}` | ''}` | `/trackpad${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/pairing`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ExpoReloadButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ReloadButton`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/patch-reanimated`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/assets`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/controls` | `/controls`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/keyboard` | `/keyboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screen` | `/screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trackpad` | `/trackpad`; params?: Router.UnknownInputParams; };
    }
  }
}
